wpa_cli -i wlan0 remove_network 0
wpa_cli -i wlan0 remove_network 1
wpa_cli -i wlan0 remove_network 2
wpa_cli -i wlan0 remove_network 3
wpa_cli -i wlan0 remove_network 4
wpa_cli -i wlan0 remove_network 5
wpa_cli -i wlan0 remove_network 6
wpa_cli -i wlan0 remove_network 7
wpa_cli -i wlan0 remove_network 8
wpa_cli -i wlan0 remove_network 9
wpa_cli -i wlan0 remove_network 10
wpa_cli -i wlan0 remove_network 11
wpa_cli -i wlan0 remove_network 12
wpa_cli -i wlan0 remove_network 13
wpa_cli -i wlan0 remove_network 14
wpa_cli -i wlan0 remove_network 15
wpa_cli -i wlan0 remove_network 16
wpa_cli -i wlan0 remove_network 17
wpa_cli -i wlan0 remove_network 18
